name: SpotValue

on:
  schedule:
    # Déclenchement toutes les 4 heures (00:00, 04:00, 08:00, 12:00, 16:00, 20:00)
    - cron: '0 */4 * * *'  # Exécution de tous les jobs toutes les 4 heures
  workflow_dispatch:  # Permet l'exécution manuelle si nécessaire

jobs:
  extract_cotes_du_jour:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "metinamerwane@gmail.com"
          git config --global user.name "Metimer"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run extract_cotes_du_jour
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python extract_cotes_du_jour.py

  extract_advanced:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "metinamerwane@gmail.com"
          git config --global user.name "Metimer"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y libgconf-2-4 libnss3 libxss1 libappindicator3-1 libindicator7

      - name: Run extract_advanced
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python extract_advanced.py

  extract_classement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "metinamerwane@gmail.com"
          git config --global user.name "Metimer"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y libgconf-2-4 libnss3 libxss1 libappindicator3-1 libindicator7

      - name: Run extract_classement
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python extract_classement.py
