name: ValueSpot

on:
  schedule:
    - cron: '0 0 * * *'  # A minuit (UTC) pour `extract_advanced`
    - cron: '0 2 * * *'  # A 2h (UTC) pour `extract_classement`
    - cron: '0 7 * * *'  # A 7h (UTC) pour `extract_cotes_du_jour`

jobs:
  extract_advanced:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run extract_advanced
        run: |
          python path/to/extract_advanced.py

  extract_classement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run extract_classement
        run: |
          python path/to/extract_classement.py

  extract_cotes_du_jour:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run extract_cotes_du_jour
        run: |
          python path/to/extract_cotes_du_jour.py
